theme = "harbor"
baseurl = "https://diabhey.github.io/"
title = "CloudOdyssey"
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

[Author]
  name = "Abhimanyu Selvan"

[permalinks]
	post = "/:year/:month/:day/:filename/"
	page = "/:filename/"

[outputs]
  section = ["JSON", "HTML"]

[[params.nav]]
  identifier = "about"
  name = "About"
  icon = "fas fa-user fa-lg"
  url = "/about/"
  weight = 1

[[params.nav]]
identifier = "bookshelf"
name = "bookshelf"
icon = "fas fa-book fa-lg"
url = "/bookshelf/"
weight = 1

[[params.nav]]
identifier = "podcasts"
name = "podcasts"
icon = "fas fa-podcast fa-lg"
url = "/podcasts/"
weight = 1

[[params.nav]]
  identifier = "tags"
  name = "Tags"
  icon = "fas fa-tag fa-lg"
  url = "tags"
  weight = 3

[[params.nav]]
identifier = "categories"
name = "Category"
icon = "fas fa-folder fa-lg"
url = "categories"
weight = 3

[[params.social]]
  name= "linkedin-in"
  url="https://linkedin.com/in/abhimanyuselvan"
  icon="fab fa-linkedin-in"  

[[params.social]]
  name= "github"
  url="https://github.com/diabhey"
  icon="fab fa-github"  

[[params.social]]
  name= "twitter"
  url="https://twitter.com/diabhey"
  icon="fab fa-twitter"  

[params]
  mainSections = ["post"]
  favicon = "favicon.ico"

[params.logo]
  url = "icon.png" # static/images/icon.png
  width = 50
  height = 50
  alt = "Logo"